### ISSUE TITLE
Incorrect formatting for currency with symbol set to 'false'

### ISSUE THREAD

**Issue by peterpajchl** [zwacky/isoCurrency#15]
As an example - the provided currency _XOF_ has symbol set to _false_ which renders the value as _false 4.00_ e.g.

Instead, it should render _XOF 4.00_.

Something like this...

```
return $filter('currency')(amount, currency && currency.symbol ? currency.symbol : currencyCode, fractionSize);
```

**Comment by zwacky** [comment]
good catch! added a fallback to currency code instead of `false`

```
return $filter('currency')(amount, currency.symbol || (currencyCode + ' '), fractionSize);
```
