### ISSUE TITLE
Requesting assiantance to fix junk characters for curreny - 'INR' in my application.

### ISSUE THREAD

**Issue by gowthamanvt** [zwacky/isoCurrency#16]
Hi,

In my applicaition, i am using currency as 'INR', but in the view its showing some junk characters as 'â‚¹0.00'. Please help me to resolve this.

**Comment by zwacky** [comment]
it looks to me as if you haven't set the encoding to utf8, as `INR` is working: http://jsfiddle.net/hq1wtnmq/

check that you have a `<meta charset="utf-8">` somewhere in your `<head>`. if this doesn't solve your issue feel free to reopen it. cheers!

**Comment by hemstreet** [comment]
This may be an IE bug, I have noticed on IE8 that INR does not show. This is because of the font issues http://stackoverflow.com/questions/11741931/indian-rupee-symbol
