### ISSUE TITLE
Currencies with postfix symbol position

### ISSUE THREAD

**Issue by nedyalkov** [zwacky/isoCurrency#17]
Some currencies like BGN, RSD, UZS have their symbol after the number. See https://en.wikipedia.org/wiki/Bulgarian_lev and https://en.wikipedia.org/wiki/Uzbekistani_som for example.

**Comment by zwacky** [comment]
that is an issue. if possible, i'd like to add the suffix/postfix completely. gotta find a resource that points that out, linked with their currency symbol.

**Comment by kdeldycke** [comment]
@zwacky why not using the CLDR metadata to render currencies? => https://www.npmjs.com/package/cldr#cldrextractnumberformatslocaleidroot-numbersystemidlatn

**Comment by zwacky** [comment]
@kdeldycke that looks very complete. although i don't have a full list of all these informations. i mainly used the infos in here: https://en.wikipedia.org/wiki/ISO_4217

also the footprint of the whole library would increase a little bit.

@nedyalkov you haven't found some either, have you?
