### ISSUE TITLE
UZS, KGS and KZT currencies have wrong symbols

### ISSUE THREAD

**Issue by nedyalkov** [zwacky/isoCurrency#18]
The symbol assigned to all the pointed currencies is 'лв' which is the actual symbol for BGN currency.

If you refer to https://en.wikipedia.org/wiki/Uzbekistani_som the symbol for UZS is 'som' (100 som), but I'm not quite sure about this. It is very weird, but they have same mistake here http://www.xe.com/currency/uzs-uzbekistani-som.

**Comment by zwacky** [comment]
looks solid!
