### ISSUE TITLE
Add the demo project to the repo

### ISSUE THREAD

**Issue by nedyalkov** [zwacky/isoCurrency#20]
It will be much easier someone to contribute if the demo project is inside the repo :smile:

**Comment by zwacky** [comment]
i like having a demo externally so you can instantly see the demo without actually having to clone the repo, npm install, ...

just fork the jsfiddle demo. could think about a github page.

**Comment by zwacky** [comment]
your point is perfectly valid! now easier to contribute using `gulp watch`.
