### ISSUE TITLE
Bower project name not valid, differs from registered package name

### ISSUE THREAD

**Issue by philBrown** [zwacky/isoCurrency#23]
Hi

Your `bower.json` project name is `isoCurrency` yet the package appears as `iso-currency` which causes a strange entry in the local `bower.json` for

```
bower install --save iso-currency
```

Results in

```
"dependencies": {
    "isoCurrency": "iso-currency#~0.2.0"
}
```

According to the [spec](https://github.com/bower/spec/blob/master/json.md#name), `name` should be...

> **Lowercase**, a-z, can contain digits, 0-9, can contain dash or dot but not start/end with them.

**Comment by zwacky** [comment]
mmmh you're right. might leave this like this and do it right for the npm registry.
what do you think, @philBrown?

edit: also bower is slowly losing traction due to npm.

**Comment by zwacky** [comment]
`npm install iso-currency`
