### ISSUE TITLE
Currency Symbol without an amount?

### ISSUE THREAD

**Issue by MattijnLahuis** [zwacky/isoCurrency#26]
Hello,

isoCurrency seems to work well so far, there's just one thing that I'm missing. There are some scenario's in which I just want to display the currency symbol itself, without any amount.

I've created a temporary workaround, by changing the last few lines in dist/isoCurrency.js like this:

var fractionSize = fraction === void 0 ? currency.fraction : fraction;
if(!amount) {
    return currency.symbol || currencyCode;
}
return $filter('currency')(amount, currency.symbol || currencyCode + ' ', fractionSize);

and calling it in my template like this:

""|isoCurrency:currency

Is there already a way of doing it? If not, is my change to isoCurrency.js acceptable as a new feature or is there an ETA on when something similar could be added?

Hope to hear from you soon

**Comment by zwacky** [comment]
wouldn't you just want to display `{{ currencyCode }}` instead putting it through the isoCurrency filter?

**Comment by Choc13** [comment]
Can you not just use the `iso4217` service directly and call `getCurrencyByCode` and then access the `symbol` property. 

This raises another point. That service should be properly exposed in it's own right as part of the API rather than being part of a `common` sub-module as the service is useful on it's own for looking up information about a currency from its code.

**Comment by zwacky** [comment]
yes, you also are able to use the `iso4217` factory in `isoCurrency.common` package.

although i don't quite see why you want to look up a currency code when you already have a currency code... 

reference: https://github.com/zwacky/isoCurrency/blob/master/src/components/iso4217.service.js

**Comment by Choc13** [comment]
In my case (and I think in @MattijnLahuis 's case also) we want to lookup just the symbol given the currency code

**Comment by zwacky** [comment]
got it.

in that case you'd go directly to the `iso4217.getCurrencyByCode('EUR')` function. I never tried to have this (`isoCurrency.common`)as an additional module dependency alongside `isoCurrency`.

if there isn't any issues, a hint in the README would be perfect, yes.

**Comment by Choc13** [comment]
I've just started to use and no issues so far :)

**Comment by jacquesdev** [comment]
@Choc13 - would be great if you could give me some pointers on how you implemented this. I also need the currency symbols.

Any pointers in the right direction would be a great help.

**Comment by zwacky** [comment]
@jacquesdev you can just include `isoCurrency.common` in your app.js, so you can use `iso4217.getCurrencyByCode('EUR')` directly.

reference https://github.com/zwacky/isoCurrency/blob/master/src/components/iso4217.service.js

i close this issue for now as it seems solved.
