### ISSUE TITLE
Installing v0.2.3 from bower does not seem to have the latest updates from master

### ISSUE THREAD

**Issue by jacquesdev** [zwacky/isoCurrency#30]
Hi @zwacky 

I have just installed version 0.2.3, but for some reason it doesn't have the latest changes currently on master?

When you get a second could you please check from your side if it looks correct?

**Comment by zwacky** [comment]
thanks for pointing out, i fixed and published it correctly now (`0.2.4`).

explanation: the release was taken from the develop branch which hasn't been merged with the latest changes. all good now. cheers
