### ISSUE TITLE
CHF symbol error

### ISSUE THREAD

**Issue by keaixx365** [zwacky/isoCurrency#33]
Hi The CHF symbol should be Fr. or SFr. or FS, but in the component is not correct. Could you help to fix it?

**Comment by zwacky** [comment]
I was thinking the same sometime, but according to https://en.wikipedia.org/wiki/Swiss_franc the have:

```
Symbol: CHF, Fr., SFr. (old)
```

I'm not fully convinced to change it to Fr. yet

**Comment by luxalpa** [comment]
The browsers `toLocaleString` also says to use CHF.

```js
(100).toLocaleString("de-CH", {style: "currency", currency: "CHF"})
```

> `"100,00 CHF"`
