### ISSUE TITLE
symbol always after amount

### ISSUE THREAD

**Issue by gabn88** [zwacky/isoCurrency#35]
I'd expect the symbol to come before the amount, but it always comes after. 

My code:
`{{activity.cost | isoCurrency:activity.cost_currency}}`

I have no idea why this is, but I tried EUR, USD, etc and it is for every symbol the same.

Using AngularJS 1.5.3 on the ionic framework (v1)

**Comment by luxalpa** [comment]
This library just uses the AngularJS `currency` filter. So your issue has to do with your configuration of AngularJS and not with this library. Try their issue tracker.

**Comment by gabn88** [comment]
Ok, thanks. I will check it out!
