### ISSUE TITLE
AngularJS Dependency

### ISSUE THREAD

**Issue by demisx** [zwacky/isoCurrency#7]
Can the ng dependency be bumped up to "^1.4"? I've been using it with 1.4.0-rcX version and didn't notice any issues.

**Comment by zwacky** [comment]
hey demisx, the `^1.2` should accept version: >= 1.2 && < 2.x

**Comment by demisx** [comment]
Yeah, I believe that would the be best approach. Currently, the bower.json says `"angular": "1.2"`.
Also, there is currently this warning installing it from bower:

``` bash
bower invalid-meta  isoCurrency is missing "ignore" entry in bower.json
```

If nothing needs to be ignored, can an empty one be added to resolve this error, so it runs clean? 
Thank you for a very helpful library, though.

**Comment by zwacky** [comment]
it doesn't say "1.2", it says "^1.2" see https://github.com/zwacky/isoCurrency/blob/master/bower.json#L21

**Comment by demisx** [comment]
My apologies. I was looking at another version.

**Comment by zwacky** [comment]
no prob :)
